### ISSUE TITLE
Sending Alerts via US Short Codes API 

### ISSUE THREAD

**Issue by wujekbogdan** [fillup/nexmo#11]
There's a [US Short Codes API](https://docs.nexmo.com/messaging/us-short-codes-api/event-based-alerts/send-event-based-alerts), but it's not implemented in the Nexmo client.

How to implement this feature? Should I simply extend the `BaseClient` class and a create a description file for it?

**Comment by fillup** [comment]
Hi @wujekbogdan , if you'd like to do that it would be appreciated. Basically we have a description file for the API definition and a class that extends BaseClient to provide the interface to it just as you mentioned. If you get hung up just let me know, happy to help. If you're not able to get to it I can also try to get it added soon too.

**Comment by wujekbogdan** [comment]
I'll try to implement it and I'll make a pull request.

**Comment by wujekbogdan** [comment]
Done: https://github.com/fillup/nexmo/pull/14
Please review.

**Comment by fillup** [comment]
Merged.
