### ISSUE TITLE
GuzzleHTTP 6.x

### ISSUE THREAD

**Issue by ooglek** [fillup/nexmo#5]
GuzzleHTTP 6.0 is out. There are some changes to the backend that may be incompatible with your implementation of GuzzleHTTP. 

Could you take a look and see if your code works with GuzzleHTTP 6.x and if so, include that in your requires?

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by glennjacobs** [comment]
:+1:

**Comment by fillup** [comment]
Yeah I'll definitely check it out. Last I tried Guzzle 6 a couple months ago it did not have the services capabilities ready yet, but it has been a couple months so I'll check it again and get back to you.

**Comment by fillup** [comment]
I just did some quick checks and browsed through the dependent packages and it looks like `guzzlehttp/command` isn't fully updated for Guzzle 6 yet (which `guzzlehttp/guzzle-services` depends on). There is a branch in progress for it, but not complete. So for now I think we just stick with 5.

I'll try to keep an eye on it, but if you see `command` updated for Guzzle 6 let me know.
